In [301]:
import pandas as pd
import sqlite3
df=pd.read_csv("../processed/cleaned_superstore.csv")
conn=sqlite3.connect("cleaned_superstore.db")
df.to_sql("sales",conn,if_exists="replace",index=False)
print("Data imported sucessfuly")

Data imported sucessfuly

## verify the table

In [302]:
query="select * from sales limit 5"
result=pd.read_sql(query,conn)
result

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,3,CA-2017-138688,6/12/2017,6/16/2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.620,2.0,0.0,6.8714
1,5,US-2016-108966,10/11/2016,10/18/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.368,2.0,0.2,2.5164
2,6,CA-2015-115812,6/9/2015,6/14/2015,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032.0,West,FUR-FU-10001487,Furniture,Furnishings,Eldon Expressions Wood and Plastic Desk Access...,48.860,7.0,0.0,14.1694
3,7,CA-2015-115812,6/9/2015,6/14/2015,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032.0,West,OFF-AR-10002833,Office Supplies,Art,Newell 322,7.280,4.0,0.0,1.9656
4,9,CA-2015-115812,6/9/2015,6/14/2015,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032.0,West,OFF-BI-10003910,Office Supplies,Binders,DXL Angle-View Binders with Locking Rings by S...,18.504,3.0,0.2,5.7825

## checking column names

In [303]:
quer="pragma table_info(sales)"
pd.read_sql(quer,conn)

    cid           name     type  notnull dflt_value  pk
0     0         Row ID  INTEGER        0       None   0
1     1       Order ID     TEXT        0       None   0
2     2     Order Date     TEXT        0       None   0
3     3      Ship Date     TEXT        0       None   0
4     4      Ship Mode     TEXT        0       None   0
5     5    Customer ID     TEXT        0       None   0
6     6  Customer Name     TEXT        0       None   0
7     7        Segment     TEXT        0       None   0
8     8        Country     TEXT        0       None   0
9     9           City     TEXT        0       None   0
10   10          State     TEXT        0       None   0
11   11    Postal Code     REAL        0       None   0
12   12         Region     TEXT        0       None   0
13   13     Product ID     TEXT        0       None   0
14   14       Category     TEXT        0       None   0
15   15   Sub-Category     TEXT        0       None   0
16   16   Product Name     TEXT        0       None   0
17   17          Sales     REAL        0       None   0
18   18       Quantity     REAL        0       None   0
19   19       Discount     REAL        0       None   0
20   20         Profit     REAL        0       None   0

## sql query

In [304]:
q="select * from sales limit 5"
pd.read_sql(q,conn)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,3,CA-2017-138688,6/12/2017,6/16/2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.620,2.0,0.0,6.8714
1,5,US-2016-108966,10/11/2016,10/18/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.368,2.0,0.2,2.5164
2,6,CA-2015-115812,6/9/2015,6/14/2015,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032.0,West,FUR-FU-10001487,Furniture,Furnishings,Eldon Expressions Wood and Plastic Desk Access...,48.860,7.0,0.0,14.1694
3,7,CA-2015-115812,6/9/2015,6/14/2015,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032.0,West,OFF-AR-10002833,Office Supplies,Art,Newell 322,7.280,4.0,0.0,1.9656
4,9,CA-2015-115812,6/9/2015,6/14/2015,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032.0,West,OFF-BI-10003910,Office Supplies,Binders,DXL Angle-View Binders with Locking Rings by S...,18.504,3.0,0.2,5.7825

## Count the total order from sales

In [305]:
q="select count(*) as total_orders from sales"
pd.read_sql(q,conn)

   total_orders
0          6082

## total sales

In [306]:
q="select sum(Sales) as total_sales from sales"
pd.read_sql(q,conn)

   total_sales
0  181797.5264

## sales by region

In [307]:
q="select region,sum(sales) as total_sales from sales group by Region"
pd.read_sql(q,conn)

    Region  total_sales
0  Central   39252.2134
1     East   53563.9190
2    South   29526.0880
3     West   59455.3060

## sales by category

In [308]:
q="select category,sum(sales) as total_sales from sales group by category"
pd.read_sql(q,conn)

          Category  total_sales
0        Furniture   28973.2084
1  Office Supplies  124337.4610
2       Technology   28486.8570

## where clause practice

In [309]:
q="select * from sales where region ='West'"
pd.read_sql(q,conn)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,3,CA-2017-138688,6/12/2017,6/16/2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.620,2.0,0.0,6.8714
1,6,CA-2015-115812,6/9/2015,6/14/2015,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032.0,West,FUR-FU-10001487,Furniture,Furnishings,Eldon Expressions Wood and Plastic Desk Access...,48.860,7.0,0.0,14.1694
2,7,CA-2015-115812,6/9/2015,6/14/2015,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032.0,West,OFF-AR-10002833,Office Supplies,Art,Newell 322,7.280,4.0,0.0,1.9656
3,9,CA-2015-115812,6/9/2015,6/14/2015,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032.0,West,OFF-BI-10003910,Office Supplies,Binders,DXL Angle-View Binders with Locking Rings by S...,18.504,3.0,0.2,5.7825
4,18,CA-2015-167164,5/13/2015,5/15/2015,Second Class,AG-10270,Alejandro Grove,Consumer,United States,West Jordan,...,84084.0,West,OFF-ST-10000107,Office Supplies,Storage,Fellowes Super Stor/Drawer,55.500,2.0,0.0,9.9900
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1885,9978,US-2017-103674,12/6/2017,12/10/2017,Standard Class,AP-10720,Anne Pryor,Home Office,United States,Los Angeles,...,90032.0,West,OFF-FA-10003467,Office Supplies,Fasteners,"Alliance Big Bands Rubber Bands, 12/Pack",13.860,7.0,0.0,0.0000
1886,9979,US-2017-103674,12/6/2017,12/10/2017,Standard Class,AP-10720,Anne Pryor,Home Office,United States,Los Angeles,...,90032.0,West,OFF-BI-10003727,Office Supplies,Binders,Avery Durable Slant Ring Binders With Label Ho...,13.376,4.0,0.2,4.6816
1887,9987,CA-2017-125794,9/29/2017,10/3/2017,Standard Class,ML-17410,Maris LaWare,Consumer,United States,Los Angeles,...,90008.0,West,TEC-AC-10003399,Technology,Accessories,Memorex Mini Travel Drive 64 GB USB 2.0 Flash ...,36.240,1.0,0.0,15.2208
1888,9991,CA-2018-121258,2/26/2018,3/3/2018,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627.0,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.960,2.0,0.0,15.6332
1889,9993,CA-2018-121258,2/26/2018,3/3/2018,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627.0,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.600,4.0,0.0,13.3200

In [310]:
q="select * from sales where sales >90"
pd.read_sql(q,conn)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,27,CA-2017-121755,1/16/2017,1/20/2017,Second Class,EH-13945,Eric Hoffmann,Consumer,United States,Los Angeles,...,90049.0,West,TEC-AC-10003027,Technology,Accessories,Imation 8GB Mini TravelDrive USB 2.0 Flash Drive,90.57,3.0,0.0,11.7741
1,211,CA-2018-135860,12/1/2018,12/7/2018,Standard Class,JH-15985,Joseph Holt,Consumer,United States,Saginaw,...,48601.0,Central,OFF-ST-10001522,Office Supplies,Storage,"Gould Plastics 18-Pocket Panel Bin, 34w x 5-1/...",91.99,1.0,0.0,3.6796
2,218,CA-2017-130162,10/28/2017,11/1/2017,Standard Class,JH-15910,Jonathan Howell,Consumer,United States,Los Angeles,...,90032.0,West,OFF-ST-10001328,Office Supplies,Storage,"Personal Filing Tote with Lid, Black/Gray",93.06,6.0,0.0,26.0568
3,444,CA-2017-115756,9/5/2017,9/7/2017,Second Class,PK-19075,Pete Kriz,Consumer,United States,Detroit,...,48227.0,Central,OFF-PA-10002222,Office Supplies,Paper,"Xerox Color Copier Paper, 11"" x 17"", Ream",91.36,4.0,0.0,42.0256
4,475,CA-2015-144666,11/9/2015,11/11/2015,Second Class,JP-15520,Jeremy Pistek,Consumer,United States,San Francisco,...,94110.0,West,OFF-ST-10001321,Office Supplies,Storage,"Decoflex Hanging Personal Folder File, Blue",92.52,6.0,0.0,24.9804
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63,9521,CA-2017-101189,2/4/2017,2/9/2017,Standard Class,JB-15400,Jennifer Braxton,Corporate,United States,Los Angeles,...,90049.0,West,OFF-ST-10004180,Office Supplies,Storage,Safco Commercial Shelving,93.02,2.0,0.0,3.7208
64,9633,CA-2018-154809,2/13/2018,2/17/2018,Standard Class,MH-17455,Mark Hamilton,Consumer,United States,Minneapolis,...,55407.0,Central,OFF-AP-10004785,Office Supplies,Appliances,Holmes Replacement Filter for HEPA Air Cleaner...,90.64,8.0,0.0,38.9752
65,9824,US-2015-164406,8/15/2015,8/19/2015,Standard Class,BD-11605,Brian Dahlen,Consumer,United States,San Francisco,...,94122.0,West,OFF-PA-10000167,Office Supplies,Paper,Xerox 1925,92.94,3.0,0.0,41.8230
66,9852,CA-2017-158155,5/2/2017,5/6/2017,Standard Class,EH-13765,Edward Hooks,Corporate,United States,New York City,...,10009.0,East,OFF-BI-10001670,Office Supplies,Binders,Vinyl Sectional Post Binders,90.48,3.0,0.2,33.9300
67,9991,CA-2018-121258,2/26/2018,3/3/2018,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627.0,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.96,2.0,0.0,15.6332

In [311]:
q="select * from sales where profit<0 "
pd.read_sql(q,conn)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,15,US-2016-118983,11/22/2016,11/26/2016,Standard Class,HP-14815,Harold Pawlan,Home Office,United States,Fort Worth,...,76106.0,Central,OFF-AP-10002311,Office Supplies,Appliances,Holmes Replacement Filter for HEPA Air Cleaner...,68.810,5.0,0.8,-123.8580
1,16,US-2016-118983,11/22/2016,11/26/2016,Standard Class,HP-14815,Harold Pawlan,Home Office,United States,Fort Worth,...,76106.0,Central,OFF-BI-10000756,Office Supplies,Binders,Storex DuraTech Recycled Plastic Frosted Binders,2.544,3.0,0.8,-3.8160
2,24,US-2018-156909,7/16/2018,7/18/2018,Second Class,SF-20065,Sandra Flanagan,Consumer,United States,Philadelphia,...,19140.0,East,FUR-CH-10002774,Furniture,Chairs,"Global Deluxe Stacking Chair, Gray",71.372,2.0,0.3,-1.0196
3,29,US-2016-150630,9/17/2016,9/21/2016,Standard Class,TB-21520,Tracy Blumstein,Consumer,United States,Philadelphia,...,19140.0,East,OFF-BI-10000474,Office Supplies,Binders,Avery Recycled Flexi-View Covers for Binding S...,9.618,2.0,0.7,-7.0532
4,33,US-2016-150630,9/17/2016,9/21/2016,Standard Class,TB-21520,Tracy Blumstein,Consumer,United States,Philadelphia,...,19140.0,East,OFF-BI-10001525,Office Supplies,Binders,"Acco Pressboard Covers with Storage Hooks, 14 ...",6.858,6.0,0.7,-5.7150
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1022,9878,US-2018-166324,4/20/2018,4/21/2018,First Class,BE-11455,Brad Eason,Home Office,United States,Cleveland,...,44105.0,East,OFF-BI-10000174,Office Supplies,Binders,Wilson Jones Clip & Carry Folder Binder Tool f...,8.700,5.0,0.7,-6.3800
1023,9904,CA-2015-122609,11/12/2015,11/18/2015,Standard Class,DP-13000,Darren Powers,Consumer,United States,Carrollton,...,75007.0,Central,FUR-FU-10004587,Furniture,Furnishings,"GE General Use Halogen Bulbs, 100 Watts, 1 Bul...",25.128,3.0,0.6,-6.9102
1024,9921,CA-2017-149272,3/15/2017,3/19/2017,Standard Class,MY-18295,Muhammed Yedwab,Corporate,United States,Bryan,...,77803.0,Central,OFF-BI-10004233,Office Supplies,Binders,"GBC Pre-Punched Binding Paper, Plastic, White,...",22.386,7.0,0.8,-35.8176
1025,9922,CA-2015-111360,11/24/2015,11/30/2015,Standard Class,AT-10435,Alyssa Tate,Home Office,United States,Akron,...,44312.0,East,OFF-BI-10003350,Office Supplies,Binders,Acco Expandable Hanging Binders,5.742,3.0,0.7,-4.5936
1026,9938,CA-2017-164889,6/3/2017,6/6/2017,Second Class,CP-12340,Christine Phan,Corporate,United States,Los Angeles,...,90049.0,West,FUR-TA-10001676,Furniture,Tables,Hon 61000 Series Interactive Training Tables,71.088,2.0,0.2,-1.7772

## order by

In [312]:
q="select [Order ID],Sales from sales order by Sales desc limit 10 "
pd.read_sql(q,conn)

         Order ID   Sales
0  US-2017-152373  93.456
1  CA-2017-139808  93.360
2  CA-2018-155607  93.344
3  CA-2017-105662  93.248
4  CA-2015-124730  93.150
5  CA-2017-130162  93.060
6  CA-2017-143406  93.032
7  CA-2015-128986  93.024
8  CA-2017-156503  93.024
9  CA-2017-101189  93.020

# HAVING Clause

## regions whith sales>40000

In [313]:
q="select region ,sum(sales) from sales group by region having sum(sales)>40000"
pd.read_sql(q,conn)

  Region  sum(sales)
0   East   53563.919
1   West   59455.306

## Categories with sales>25000

In [314]:
q="select category,sum(sales) from sales group by category having sum(sales)>25000"
pd.read_sql(q,conn)

          Category   sum(sales)
0        Furniture   28973.2084
1  Office Supplies  124337.4610
2       Technology   28486.8570

## Categories with avg profit >5

In [315]:
q="select category,avg(profit) as AVG_Profit from sales group by category having avg(profit)>5"
pd.read_sql(q,conn)

          Category  AVG_Profit
0  Office Supplies    5.181476
1       Technology    7.355571

## max() function

In [316]:
q="select max(sales) as highest_Sale from sales"
pd.read_sql(q,conn)

   highest_Sale
0        93.456

## min() function

In [317]:
q="select min(sales) as lowest_Sale from sales"
pd.read_sql(q,conn)

   lowest_Sale
0        0.444

## count with group by

In [318]:
q="select region,count(*) total_orders from sales group by region"
pd.read_sql(q,conn)

    Region  total_orders
0  Central          1456
1     East          1746
2    South           990
3     West          1890

In [319]:
q = """
SELECT Region,
       COUNT(*) AS Total_Orders
FROM sales
GROUP BY Region
HAVING COUNT(*) > 1000
"""

pd.read_sql(q, conn)

    Region  Total_Orders
0  Central          1456
1     East          1746
2     West          1890

## Insight:
East, West, and Central have more than 1000 orders.
South has fewer than 1000 orders and may require business attention.

In [320]:
q = """
SELECT Category,
       AVG(Sales) AS Avg_Sales
FROM sales
GROUP BY Category
HAVING AVG(Sales) > 30
"""

pd.read_sql(q, conn)

     Category  Avg_Sales
0   Furniture  37.145139
1  Technology  46.776448

## Insight:
Technology has the highest average sales per transaction, indicating stronger revenue generation per order.

Furniture also maintains an average sales value above 30, making it an important revenue contributor.

In [321]:
q = """
SELECT Region,
       SUM(Sales) AS Total_Sales
FROM sales
GROUP BY Region
ORDER BY Total_Sales DESC
LIMIT 3
"""

pd.read_sql(q, conn)

    Region  Total_Sales
0     West   59455.3060
1     East   53563.9190
2  Central   39252.2134

## Insight:
West region generated the highest total sales, followed by East and Central.

These regions contribute significantly to overall business revenue and should be prioritized for growth strategies.

# Key Business Findings

1. West region generated the highest sales and order volume.
2. Technology category achieved the highest average profit.
3. South region had the lowest order count.
4. Furniture and Technology categories recorded average sales above 30.
5. Office Supplies and Technology maintained average profits greater than 5.

## Subqueries

In [322]:
q="select * from sales where sales>(select avg(sales) from sales) limit 5"
pd.read_sql(q,conn)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,6,CA-2015-115812,6/9/2015,6/14/2015,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032.0,West,FUR-FU-10001487,Furniture,Furnishings,Eldon Expressions Wood and Plastic Desk Access...,48.860,7.0,0.0,14.1694
1,15,US-2016-118983,11/22/2016,11/26/2016,Standard Class,HP-14815,Harold Pawlan,Home Office,United States,Fort Worth,...,76106.0,Central,OFF-AP-10002311,Office Supplies,Appliances,Holmes Replacement Filter for HEPA Air Cleaner...,68.810,5.0,0.8,-123.8580
2,18,CA-2015-167164,5/13/2015,5/15/2015,Second Class,AG-10270,Alejandro Grove,Consumer,United States,West Jordan,...,84084.0,West,OFF-ST-10000107,Office Supplies,Storage,Fellowes Super Stor/Drawer,55.500,2.0,0.0,9.9900
3,23,CA-2017-137330,12/9/2017,12/13/2017,Standard Class,KB-16585,Ken Black,Corporate,United States,Fremont,...,68025.0,Central,OFF-AP-10001492,Office Supplies,Appliances,"Acco Six-Outlet Power Strip, 4' Cord Length",60.340,7.0,0.0,15.6884
4,24,US-2018-156909,7/16/2018,7/18/2018,Second Class,SF-20065,Sandra Flanagan,Consumer,United States,Philadelphia,...,19140.0,East,FUR-CH-10002774,Furniture,Chairs,"Global Deluxe Stacking Chair, Gray",71.372,2.0,0.3,-1.0196

In [323]:
q="select [order ID] from sales where profit>(select avg(profit) from sales)"
pd.read_sql(q,conn)

            Order ID
0     CA-2017-138688
1     CA-2015-115812
2     CA-2015-115812
3     CA-2018-114412
4     CA-2015-167164
...              ...
3147  CA-2016-100251
3148  CA-2017-125794
3149  CA-2018-163629
3150  CA-2018-121258
3151  CA-2018-121258

[3152 rows x 1 columns]

## CTE-Common Table Expression

In [324]:
q="with regionsales as (select region,sum(sales) as total_sales from sales group by region) select *from regionsales"
pd.read_sql(q,conn)

    region  total_sales
0  Central   39252.2134
1     East   53563.9190
2    South   29526.0880
3     West   59455.3060

## Top Region Using CTE

In [325]:
q="with regionsales as (select region,sum(sales) as total_sales from sales group by region) select *from regionsales order by total_sales desc limit 1"
pd.read_sql(q,conn)

  region  total_sales
0   West    59455.306

## Window Functions

   ## ROW_NUMBER()

In [326]:
q = """
SELECT Region,
       Sales,
       ROW_NUMBER() OVER
       (
           ORDER BY Sales DESC
       ) AS Row_Num
FROM sales
"""
pd.read_sql(q, conn)

       Region   Sales  Row_Num
0     Central  93.456        1
1        West  93.360        2
2        East  93.344        3
3       South  93.248        4
4        East  93.150        5
...       ...     ...      ...
6077  Central   0.876     6078
6078     East   0.852     6079
6079  Central   0.836     6080
6080  Central   0.556     6081
6081  Central   0.444     6082

[6082 rows x 3 columns]

  ## RANK()

In [327]:
q = """
SELECT Region,
       Sales,
       RANK() OVER
       (
           ORDER BY Sales DESC
       ) AS Sales_Rank
FROM sales
"""
pd.read_sql(q, conn)

       Region   Sales  Sales_Rank
0     Central  93.456           1
1        West  93.360           2
2        East  93.344           3
3       South  93.248           4
4        East  93.150           5
...       ...     ...         ...
6077  Central   0.876        6078
6078     East   0.852        6079
6079  Central   0.836        6080
6080  Central   0.556        6081
6081  Central   0.444        6082

[6082 rows x 3 columns]

## LAG()

In [328]:
q="select region,sales,lag(sales) over(order by sales desc) as previous_sale from sales"
pd.read_sql(q, conn)

       Region   Sales  previous_sale
0     Central  93.456            NaN
1        West  93.360         93.456
2        East  93.344         93.360
3       South  93.248         93.344
4        East  93.150         93.248
...       ...     ...            ...
6077  Central   0.876          0.898
6078     East   0.852          0.876
6079  Central   0.836          0.852
6080  Central   0.556          0.836
6081  Central   0.444          0.556

[6082 rows x 3 columns]

## LEAD()

In [329]:
q="select region,sales,lead(sales) over(order by sales desc) as Next_sale from sales"
pd.read_sql(q, conn)

       Region   Sales  Next_sale
0     Central  93.456     93.360
1        West  93.360     93.344
2        East  93.344     93.248
3       South  93.248     93.150
4        East  93.150     93.060
...       ...     ...        ...
6077  Central   0.876      0.852
6078     East   0.852      0.836
6079  Central   0.836      0.556
6080  Central   0.556      0.444
6081  Central   0.444        NaN

[6082 rows x 3 columns]

## Create a view - HighSales

In [330]:
conn.execute("DROP VIEW IF EXISTS HighSales")

q = """
CREATE VIEW HighSales AS
SELECT *
FROM sales
WHERE Sales > 50 
"""
conn.execute(q)
print("View created successfully!")

View created successfully!

## verifying the view

In [331]:
pd.read_sql("""
SELECT *
FROM HighSales limit 5
""", conn)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,15,US-2016-118983,11/22/2016,11/26/2016,Standard Class,HP-14815,Harold Pawlan,Home Office,United States,Fort Worth,...,76106.0,Central,OFF-AP-10002311,Office Supplies,Appliances,Holmes Replacement Filter for HEPA Air Cleaner...,68.810,5.0,0.8,-123.8580
1,18,CA-2015-167164,5/13/2015,5/15/2015,Second Class,AG-10270,Alejandro Grove,Consumer,United States,West Jordan,...,84084.0,West,OFF-ST-10000107,Office Supplies,Storage,Fellowes Super Stor/Drawer,55.500,2.0,0.0,9.9900
2,23,CA-2017-137330,12/9/2017,12/13/2017,Standard Class,KB-16585,Ken Black,Corporate,United States,Fremont,...,68025.0,Central,OFF-AP-10001492,Office Supplies,Appliances,"Acco Six-Outlet Power Strip, 4' Cord Length",60.340,7.0,0.0,15.6884
3,24,US-2018-156909,7/16/2018,7/18/2018,Second Class,SF-20065,Sandra Flanagan,Consumer,United States,Philadelphia,...,19140.0,East,FUR-CH-10002774,Furniture,Chairs,"Global Deluxe Stacking Chair, Gray",71.372,2.0,0.3,-1.0196
4,27,CA-2017-121755,1/16/2017,1/20/2017,Second Class,EH-13945,Eric Hoffmann,Consumer,United States,Los Angeles,...,90049.0,West,TEC-AC-10003027,Technology,Accessories,Imation 8GB Mini TravelDrive USB 2.0 Flash Drive,90.570,3.0,0.0,11.7741